import Darwin
import Foundation

/// Bounded failures produced before the restore journal publishes a new intent.
/// No case contains a caller path or an arbitrary dependency error string.
enum DescriptorNPMQuarantineRestorePreflightFailure: Error, Equatable, Sendable {
  case cancelled
  case invalidCurrentAccount
  case invalidHome
  case invalidQuarantineTransactionID
  case homeUnavailable(CleanupQuarantineSystemFailure)
  case homeUnsafe
  case rootUnavailable(CleanupQuarantineSystemFailure)
  case rootUnsafe
  case quarantineRootUnavailable(CleanupQuarantineSystemFailure)
  case quarantineRootUnsafe
  case restoreIdentifierUnavailable
  case restoreIdentifierCollisionLimitExceeded
  case restore(DescriptorQuarantineRestoreFailure)
  case authorization(CleanupQuarantineRestoreAuthorizationError)
  case invalidClaim
}

struct DescriptorNPMQuarantineRestorePreflightHooks: Sendable {
  var beforeFinalParentValidation: @Sendable () throws -> Void
  var beforeOpeningQuarantinedItem: @Sendable () throws -> Void
  var beforeExecutingValidatedClaim: @Sendable () throws -> Void

  init(
    beforeFinalParentValidation: @escaping @Sendable () throws -> Void = {},
    beforeOpeningQuarantinedItem: @escaping @Sendable () throws -> Void = {},
    beforeExecutingValidatedClaim: @escaping @Sendable () throws -> Void = {}
  ) {
    self.beforeFinalParentValidation = beforeFinalParentValidation
    self.beforeOpeningQuarantinedItem = beforeOpeningQuarantinedItem
    self.beforeExecutingValidatedClaim = beforeExecutingValidatedClaim
  }
}

/// Injectable seams remain internal. Production path discovery is fixed to the
/// current account's passwd home and never accepts a caller-selected root.
struct DescriptorNPMQuarantineRestorePreflightDependencies: Sendable {
  typealias Checkpoint = @Sendable () throws -> Void
  typealias RawHomeProvider = @Sendable () -> RuleObserved<[UInt8]>
  typealias AccountUIDProvider = @Sendable () -> RuleObserved<uid_t>
  typealias NonceProvider = @Sendable (Int) -> [UInt8]?
  typealias ACLChecker =
    @Sendable (Int32) -> DescriptorQuarantineDependencyResult<Bool>
  typealias BeginAuthorization =
    @Sendable (
      CleanupQuarantineRestorePreparedEvidence
    ) throws -> CleanupQuarantineRestoreAuthorizationSession

  var checkpoint: Checkpoint
  var rawHomeProvider: RawHomeProvider
  var accountUIDProvider: AccountUIDProvider
  var nonceBytes: NonceProvider
  var hasExtendedACL: ACLChecker
  var journal: DescriptorQuarantineRestoreJournal
  var beginAuthorization: BeginAuthorization
  var hooks: DescriptorNPMQuarantineRestorePreflightHooks

  init(
    checkpoint: @escaping Checkpoint = { try Task.checkCancellation() },
    rawHomeProvider: @escaping RawHomeProvider = { currentUIDRawHome() },
    accountUIDProvider: @escaping AccountUIDProvider = { currentNonRootAccountUID() },
    nonceBytes: @escaping NonceProvider = descriptorRestoreRandomNonce,
    hasExtendedACL: @escaping ACLChecker = descriptorRestoreHasExtendedACL,
    journal: DescriptorQuarantineRestoreJournal = DescriptorQuarantineRestoreJournal(),
    beginAuthorization: @escaping BeginAuthorization = {
      try CleanupQuarantineRestoreAuthorizer().beginAttempt(for: $0)
    },
    hooks: DescriptorNPMQuarantineRestorePreflightHooks =
      DescriptorNPMQuarantineRestorePreflightHooks()
  ) {
    self.checkpoint = checkpoint
    self.rawHomeProvider = rawHomeProvider
    self.accountUIDProvider = accountUIDProvider
    self.nonceBytes = nonceBytes
    self.hasExtendedACL = hasExtendedACL
    self.journal = journal
    self.beginAuthorization = beginAuthorization
    self.hooks = hooks
  }
}

/// Opens only passwd-home/`.npm`/`.devsift-quarantine-v1` and keeps every
/// descriptor live across the synchronous journal or restore call.
struct DescriptorNPMQuarantineRestorePreflight: Sendable {
  static let maximumRestoreIdentifierAttempts = 16

  private static let npmRootBytes = Array(".npm".utf8)
  private static let sourceBytes = Array("_cacache".utf8)

  private let dependencies: DescriptorNPMQuarantineRestorePreflightDependencies

  init(
    dependencies: DescriptorNPMQuarantineRestorePreflightDependencies =
      DescriptorNPMQuarantineRestorePreflightDependencies()
  ) {
    self.dependencies = dependencies
  }

  /// Discovers canonical journal evidence and creates one process-local
  /// confirmation session. The restore transaction identifier is generated by
  /// Core; callers provide only the canonical quarantine transaction selector.
  func prepare(
    quarantineTransactionID: String,
    expectedCanonicalIntentBytes: Data? = nil,
    expectedCanonicalReceiptBytes: Data? = nil
  ) -> Result<
    CleanupQuarantineRestoreAuthorizationSession,
    DescriptorNPMQuarantineRestorePreflightFailure
  > {
    guard descriptorRestoreIsLowercaseHexIdentifier(quarantineTransactionID) else {
      return .failure(.invalidQuarantineTransactionID)
    }
    guard
      (expectedCanonicalIntentBytes == nil) == (expectedCanonicalReceiptBytes == nil)
    else {
      return .failure(.invalidClaim)
    }

    return withValidatedParents(expectedIntent: nil) { recoveryRequest in
      for attempt in 0..<Self.maximumRestoreIdentifierAttempts {
        do {
          try cancellationCheckpoint()
        } catch {
          return .failure(.cancelled)
        }
        guard
          let nonce = dependencies.nonceBytes(attempt),
          let restoreTransactionID = descriptorRestoreTransactionIdentifier(nonce),
          restoreTransactionID != quarantineTransactionID
        else {
          if attempt + 1 < Self.maximumRestoreIdentifierAttempts {
            continue
          }
          return .failure(.restoreIdentifierUnavailable)
        }

        let prepared: CleanupQuarantineRestorePreparedEvidence
        switch dependencies.journal.prepare(
          DescriptorQuarantineRestorePreparationRequest(
            recoveryRequest: recoveryRequest,
            quarantineTransactionID: quarantineTransactionID,
            restoreTransactionID: restoreTransactionID,
            expectedCanonicalQuarantineIntentBytes: expectedCanonicalIntentBytes,
            expectedCanonicalQuarantineReceiptBytes: expectedCanonicalReceiptBytes
          )
        ) {
        case .success(let evidence):
          prepared = evidence
        case .failure(.invalidClaim):
          guard attempt + 1 < Self.maximumRestoreIdentifierAttempts else {
            return .failure(.restoreIdentifierCollisionLimitExceeded)
          }
          continue
        case .failure(let failure):
          return .failure(.restore(failure))
        }

        do {
          try cancellationCheckpoint()
          return .success(try dependencies.beginAuthorization(prepared))
        } catch is CancellationError {
          return .failure(.cancelled)
        } catch let failure as CleanupQuarantineRestoreAuthorizationError {
          return .failure(.authorization(failure))
        } catch {
          return .failure(.authorization(.invalidPreparedEvidence))
        }
      }
      return .failure(.restoreIdentifierCollisionLimitExceeded)
    }
  }

  /// Reopens every path and the exact receipt-bound item, then calls the
  /// concrete restorer synchronously while those descriptors remain held. The
  /// restorer owns durable-intent publication and the rename linearization
  /// boundary; this preflight performs no mutation itself.
  func executeValidatedClaim(
    _ claim: CleanupQuarantineRestoreExecutionClaim,
    using restorer: DescriptorExclusiveQuarantineRestorer
  ) -> Result<
    CleanupQuarantineRestoreReport,
    DescriptorNPMQuarantineRestorePreflightFailure
  > {
    let projection: DescriptorRestoreClaimProjection
    do {
      projection = try validateExecutionClaim(claim)
      try cancellationCheckpoint()
    } catch is CancellationError {
      return .failure(.cancelled)
    } catch {
      return .failure(.invalidClaim)
    }

    return withValidatedParents(expectedIntent: projection.intent) { recoveryRequest in
      let sourceComponent = DescriptorPathComponent(Self.sourceBytes)!
      do {
        try cancellationCheckpoint()
        switch try descriptorRestoreObserveName(
          at: recoveryRequest.rootDescriptor,
          component: sourceComponent
        ) {
        case .missing:
          break
        case .present:
          return .failure(.restore(.sourceNameOccupied))
        }

        try dependencies.hooks.beforeOpeningQuarantinedItem()
        try cancellationCheckpoint()
      } catch is CancellationError {
        return .failure(.cancelled)
      } catch let failure as DescriptorNPMQuarantineRestorePreflightFailure {
        return .failure(failure)
      } catch {
        return .failure(.restore(.quarantinedItemChanged))
      }

      let itemComponent = DescriptorPathComponent(projection.intent.quarantineItemComponent)!
      let itemDescriptor: Int32
      do {
        itemDescriptor = try descriptorOpenTrustedDirectory(
          at: recoveryRequest.quarantineRootDescriptor,
          component: itemComponent
        )
      } catch is CancellationError {
        return .failure(.cancelled)
      } catch DescriptorObservationError.posix(ENOENT) {
        return .failure(.restore(.quarantinedItemMissing))
      } catch {
        return .failure(.restore(.quarantinedItemChanged))
      }
      defer { descriptorCloseIgnoringErrors(itemDescriptor) }

      do {
        let held = try DescriptorStatSnapshot.read(from: itemDescriptor)
        let named = try DescriptorStatSnapshot.read(
          at: recoveryRequest.quarantineRootDescriptor,
          component: itemComponent
        )
        guard
          descriptorRestoreSnapshotsEqual(held, named),
          descriptorRestoreMatchesHistoricalParent(
            held,
            expected: projection.intent.candidateBinding
          ),
          held.kind == .directory,
          held.ownerUID == recoveryRequest.accountUID,
          held.identity.device == projection.intent.npmRootBinding.device,
          held.permissionMode & mode_t(0o022) == 0,
          held.flags == 0
        else {
          return .failure(.restore(.quarantinedItemUnsafe))
        }
        switch dependencies.hasExtendedACL(itemDescriptor) {
        case .success(false):
          break
        case .success(true):
          return .failure(.restore(.quarantinedItemUnsafe))
        case .failure:
          return .failure(.restore(.quarantinedItemChanged))
        }

        try dependencies.hooks.beforeExecutingValidatedClaim()
        try cancellationCheckpoint()
        let finalHeld = try DescriptorStatSnapshot.read(from: itemDescriptor)
        let finalNamed = try DescriptorStatSnapshot.read(
          at: recoveryRequest.quarantineRootDescriptor,
          component: itemComponent
        )
        guard
          descriptorRestoreSnapshotsEqual(finalHeld, held),
          descriptorRestoreSnapshotsEqual(finalNamed, held)
        else {
          return .failure(.restore(.quarantinedItemChanged))
        }
        switch dependencies.hasExtendedACL(itemDescriptor) {
        case .success(false):
          break
        case .success(true):
          return .failure(.restore(.quarantinedItemUnsafe))
        case .failure:
          return .failure(.restore(.quarantinedItemChanged))
        }
      } catch is CancellationError {
        return .failure(.cancelled)
      } catch {
        return .failure(.restore(.quarantinedItemChanged))
      }

      let scope = DescriptorNPMQuarantineRestoreScope(
        heldRootDescriptor: recoveryRequest.rootDescriptor,
        heldQuarantineRootDescriptor: recoveryRequest.quarantineRootDescriptor,
        heldQuarantinedItemDescriptor: itemDescriptor,
        recoveryRequest: recoveryRequest,
        claim: claim,
        ruleRevision: projection.ruleRevision
      )
      return .success(restorer.restore(scope))
    }
  }

  private func withValidatedParents<ResultValue>(
    expectedIntent: QuarantineRestoreJournalIntentV1?,
    _ body: (DescriptorQuarantineJournalRecoveryRequest) -> Result<
      ResultValue,
      DescriptorNPMQuarantineRestorePreflightFailure
    >
  ) -> Result<ResultValue, DescriptorNPMQuarantineRestorePreflightFailure> {
    do {
      try cancellationCheckpoint()
    } catch {
      return .failure(.cancelled)
    }

    let accountUID: uid_t
    switch dependencies.accountUIDProvider() {
    case .known(let value)
    where
      value != 0 && Darwin.getuid() == value && Darwin.geteuid() == value:
      accountUID = value
    case .known, .unknown:
      return .failure(.invalidCurrentAccount)
    }

    let rawHome: [UInt8]
    switch dependencies.rawHomeProvider() {
    case .known(let value):
      rawHome = value
    case .unknown:
      return .failure(.invalidHome)
    }
    guard
      let homePath = DescriptorAbsolutePath(rawBytes: rawHome),
      !homePath.components.isEmpty,
      let npmComponent = DescriptorPathComponent(Self.npmRootBytes),
      let quarantineComponent = DescriptorPathComponent(
        DescriptorExclusiveQuarantineMover.quarantineRootBytes
      )
    else {
      return .failure(.invalidHome)
    }

    let homeDescriptor: Int32
    let homeSnapshot: DescriptorStatSnapshot
    do {
      (homeDescriptor, homeSnapshot) = try openValidatedHome(
        components: homePath.components,
        accountUID: accountUID
      )
    } catch is CancellationError {
      return .failure(.cancelled)
    } catch let failure as DescriptorNPMQuarantineRestorePreflightFailure {
      return .failure(failure)
    } catch {
      return .failure(.homeUnavailable(descriptorJournalFailure(for: error)))
    }
    defer { descriptorCloseIgnoringErrors(homeDescriptor) }

    let rootDescriptor: Int32
    do {
      rootDescriptor = try descriptorOpenTrustedDirectory(
        at: homeDescriptor,
        component: npmComponent
      )
    } catch is CancellationError {
      return .failure(.cancelled)
    } catch {
      return .failure(.rootUnavailable(descriptorJournalFailure(for: error)))
    }
    defer { descriptorCloseIgnoringErrors(rootDescriptor) }

    let rootSnapshot: DescriptorStatSnapshot
    do {
      rootSnapshot = try validateRoot(
        descriptor: rootDescriptor,
        namedAt: homeDescriptor,
        component: npmComponent,
        homeSnapshot: homeSnapshot,
        accountUID: accountUID
      )
    } catch is CancellationError {
      return .failure(.cancelled)
    } catch let failure as DescriptorNPMQuarantineRestorePreflightFailure {
      return .failure(failure)
    } catch {
      return .failure(.rootUnavailable(descriptorJournalFailure(for: error)))
    }

    let quarantineDescriptor: Int32
    do {
      quarantineDescriptor = try descriptorOpenTrustedDirectory(
        at: rootDescriptor,
        component: quarantineComponent
      )
    } catch is CancellationError {
      return .failure(.cancelled)
    } catch {
      return .failure(.quarantineRootUnavailable(descriptorJournalFailure(for: error)))
    }
    defer { descriptorCloseIgnoringErrors(quarantineDescriptor) }

    let quarantineSnapshot: DescriptorStatSnapshot
    do {
      quarantineSnapshot = try validateQuarantineRoot(
        descriptor: quarantineDescriptor,
        namedAt: rootDescriptor,
        component: quarantineComponent,
        rootSnapshot: rootSnapshot,
        accountUID: accountUID
      )
      try dependencies.hooks.beforeFinalParentValidation()
      try cancellationCheckpoint()
      let finalHomeSnapshot = try DescriptorStatSnapshot.read(from: homeDescriptor)
      guard descriptorRestoreSnapshotsEqual(finalHomeSnapshot, homeSnapshot) else {
        throw DescriptorNPMQuarantineRestorePreflightFailure.homeUnsafe
      }
      let finalRootSnapshot = try validateRoot(
        descriptor: rootDescriptor,
        namedAt: homeDescriptor,
        component: npmComponent,
        homeSnapshot: finalHomeSnapshot,
        accountUID: accountUID
      )
      guard descriptorRestoreSnapshotsEqual(finalRootSnapshot, rootSnapshot) else {
        throw DescriptorNPMQuarantineRestorePreflightFailure.rootUnsafe
      }
      let finalQuarantineSnapshot = try validateQuarantineRoot(
        descriptor: quarantineDescriptor,
        namedAt: rootDescriptor,
        component: quarantineComponent,
        rootSnapshot: finalRootSnapshot,
        accountUID: accountUID
      )
      guard
        descriptorRestoreSnapshotsEqual(finalQuarantineSnapshot, quarantineSnapshot)
      else {
        throw DescriptorNPMQuarantineRestorePreflightFailure.quarantineRootUnsafe
      }
      try validateAbsoluteContainment(
        homeComponents: homePath.components,
        npmComponent: npmComponent,
        quarantineComponent: quarantineComponent,
        rootSnapshot: finalRootSnapshot,
        quarantineSnapshot: finalQuarantineSnapshot
      )
    } catch is CancellationError {
      return .failure(.cancelled)
    } catch let failure as DescriptorNPMQuarantineRestorePreflightFailure {
      return .failure(failure)
    } catch {
      return .failure(.quarantineRootUnavailable(descriptorJournalFailure(for: error)))
    }

    if let expectedIntent {
      guard
        descriptorRestoreMatchesHistoricalParent(
          rootSnapshot,
          expected: expectedIntent.npmRootBinding
        ),
        descriptorRestoreMatchesHistoricalParent(
          quarantineSnapshot,
          expected: expectedIntent.quarantineRootBinding
        )
      else {
        return .failure(.invalidClaim)
      }
    }

    let request = DescriptorQuarantineJournalRecoveryRequest(
      rootDescriptor: rootDescriptor,
      quarantineRootDescriptor: quarantineDescriptor,
      quarantineRootComponent: quarantineComponent,
      absoluteRootComponents: homePath.components + [npmComponent],
      homeComponentCount: homePath.components.count,
      accountUID: accountUID
    )
    return body(request)
  }

  private func openValidatedHome(
    components: [DescriptorPathComponent],
    accountUID: uid_t
  ) throws -> (Int32, DescriptorStatSnapshot) {
    var traversal = try descriptorOpenRoot(
      URL(fileURLWithPath: "/", isDirectory: true)
    )
    do {
      var finalSnapshot: DescriptorStatSnapshot?
      for (index, component) in components.enumerated() {
        try cancellationCheckpoint()
        let namedBefore = try DescriptorStatSnapshot.read(
          at: traversal,
          component: component
        )
        let child = try descriptorOpenTrustedDirectory(
          at: traversal,
          component: component
        )
        let held = try DescriptorStatSnapshot.read(from: child)
        let namedAfter = try DescriptorStatSnapshot.read(
          at: traversal,
          component: component
        )
        guard
          descriptorRestoreSnapshotsEqual(namedBefore, held),
          descriptorRestoreSnapshotsEqual(namedAfter, held)
        else {
          descriptorCloseIgnoringErrors(child)
          throw DescriptorNPMQuarantineRestorePreflightFailure.homeUnsafe
        }
        descriptorCloseIgnoringErrors(traversal)
        traversal = child
        if index + 1 == components.count {
          finalSnapshot = held
        }
      }
      guard let snapshot = finalSnapshot else {
        throw DescriptorNPMQuarantineRestorePreflightFailure.invalidHome
      }
      guard
        snapshot.kind == .directory,
        snapshot.ownerUID == accountUID,
        snapshot.permissionMode & mode_t(0o022) == 0,
        snapshot.flags == 0
      else {
        throw DescriptorNPMQuarantineRestorePreflightFailure.homeUnsafe
      }
      return (traversal, snapshot)
    } catch {
      descriptorCloseIgnoringErrors(traversal)
      throw error
    }
  }

  private func validateRoot(
    descriptor: Int32,
    namedAt parentDescriptor: Int32,
    component: DescriptorPathComponent,
    homeSnapshot: DescriptorStatSnapshot,
    accountUID: uid_t
  ) throws -> DescriptorStatSnapshot {
    let held = try DescriptorStatSnapshot.read(from: descriptor)
    let named = try DescriptorStatSnapshot.read(
      at: parentDescriptor,
      component: component
    )
    guard
      descriptorRestoreSnapshotsEqual(held, named),
      held.kind == .directory,
      held.identity.device == homeSnapshot.identity.device,
      held.ownerUID == accountUID,
      held.permissionMode & mode_t(0o022) == 0,
      held.flags == 0
    else {
      throw DescriptorNPMQuarantineRestorePreflightFailure.rootUnsafe
    }
    switch dependencies.hasExtendedACL(descriptor) {
    case .success(false):
      return held
    case .success(true):
      throw DescriptorNPMQuarantineRestorePreflightFailure.rootUnsafe
    case .failure(let failure):
      throw DescriptorNPMQuarantineRestorePreflightFailure.rootUnavailable(failure)
    }
  }

  private func validateQuarantineRoot(
    descriptor: Int32,
    namedAt parentDescriptor: Int32,
    component: DescriptorPathComponent,
    rootSnapshot: DescriptorStatSnapshot,
    accountUID: uid_t
  ) throws -> DescriptorStatSnapshot {
    let held = try DescriptorStatSnapshot.read(from: descriptor)
    let named = try DescriptorStatSnapshot.read(
      at: parentDescriptor,
      component: component
    )
    guard
      descriptorRestoreSnapshotsEqual(held, named),
      held.kind == .directory,
      held.identity.device == rootSnapshot.identity.device,
      held.ownerUID == accountUID,
      held.permissionMode == mode_t(0o700),
      held.flags == 0
    else {
      throw DescriptorNPMQuarantineRestorePreflightFailure.quarantineRootUnsafe
    }
    switch dependencies.hasExtendedACL(descriptor) {
    case .success(false):
      return held
    case .success(true):
      throw DescriptorNPMQuarantineRestorePreflightFailure.quarantineRootUnsafe
    case .failure(let failure):
      throw DescriptorNPMQuarantineRestorePreflightFailure.quarantineRootUnavailable(failure)
    }
  }

  private func validateAbsoluteContainment(
    homeComponents: [DescriptorPathComponent],
    npmComponent: DescriptorPathComponent,
    quarantineComponent: DescriptorPathComponent,
    rootSnapshot: DescriptorStatSnapshot,
    quarantineSnapshot: DescriptorStatSnapshot
  ) throws {
    let rootFromSlash = try descriptorSnapshot(
      atAbsoluteComponents: homeComponents + [npmComponent],
      homeComponentCount: homeComponents.count
    )
    let quarantineFromSlash = try descriptorSnapshot(
      atAbsoluteComponents: homeComponents + [npmComponent, quarantineComponent],
      homeComponentCount: homeComponents.count
    )
    guard descriptorRestoreSnapshotsEqual(rootFromSlash, rootSnapshot) else {
      throw DescriptorNPMQuarantineRestorePreflightFailure.rootUnsafe
    }
    guard descriptorRestoreSnapshotsEqual(quarantineFromSlash, quarantineSnapshot) else {
      throw DescriptorNPMQuarantineRestorePreflightFailure.quarantineRootUnsafe
    }
  }

  private func validateExecutionClaim(
    _ claim: CleanupQuarantineRestoreExecutionClaim
  ) throws -> DescriptorRestoreClaimProjection {
    let evidence = claim.evidence
    let quarantineIntent = try QuarantineJournalV1Codec.decodeIntent(
      evidence.canonicalQuarantineIntentBytes
    )
    let quarantineReceipt = try QuarantineJournalV1Codec.decodeReceipt(
      evidence.canonicalQuarantineReceiptBytes,
      matchingIntentBytes: evidence.canonicalQuarantineIntentBytes
    )
    guard quarantineReceipt.outcome == .quarantined else {
      throw DescriptorNPMQuarantineRestorePreflightFailure.invalidClaim
    }
    try QuarantineRestoreJournalV1Codec.validate(
      evidence.restoreIntent,
      canonicalQuarantineIntentBytes: evidence.canonicalQuarantineIntentBytes,
      canonicalQuarantineReceiptBytes: evidence.canonicalQuarantineReceiptBytes
    )
    let subject = claim.confirmation.request.subject
    guard
      evidence.restoreIntent.restorePolicyRevision
        == QuarantineRestoreJournalIntentV1.currentRestorePolicyRevision,
      claim.confirmation.statement == claim.confirmation.request.requiredStatement,
      claim.confirmation.statement.policyRevision == 1,
      subject.restoreTransactionID == evidence.restoreIntent.restoreTransactionID,
      subject.quarantineTransactionID == evidence.restoreIntent.quarantineTransactionID,
      subject.originalPath.rawComponents == evidence.restoreIntent.sourceComponents,
      subject.quarantineItemPath.rawComponents
        == [
          DescriptorExclusiveQuarantineMover.quarantineRootBytes,
          evidence.restoreIntent.quarantineItemComponent,
        ],
      subject.responsibleTool == "npm",
      let identifier = RuleIdentifier(rawValue: quarantineIntent.policy.npmRule.identifier),
      let version = RuleVersion(rawValue: quarantineIntent.policy.npmRule.version)
    else {
      throw DescriptorNPMQuarantineRestorePreflightFailure.invalidClaim
    }
    return DescriptorRestoreClaimProjection(
      intent: evidence.restoreIntent,
      ruleRevision: RuleRevision(identifier: identifier, version: version)
    )
  }

  private func cancellationCheckpoint() throws {
    do {
      try dependencies.checkpoint()
      try Task.checkCancellation()
    } catch is CancellationError {
      throw CancellationError()
    } catch {
      throw DescriptorNPMQuarantineRestorePreflightFailure.cancelled
    }
  }
}

private struct DescriptorRestoreClaimProjection {
  let intent: QuarantineRestoreJournalIntentV1
  let ruleRevision: RuleRevision
}

private enum DescriptorRestoreObservedName {
  case missing
  case present
}

private func descriptorRestoreObserveName(
  at parentDescriptor: Int32,
  component: DescriptorPathComponent
) throws -> DescriptorRestoreObservedName {
  do {
    _ = try DescriptorStatSnapshot.read(at: parentDescriptor, component: component)
    return .present
  } catch DescriptorObservationError.posix(ENOENT) {
    return .missing
  }
}

private func descriptorRestoreSnapshotsEqual(
  _ left: DescriptorStatSnapshot,
  _ right: DescriptorStatSnapshot
) -> Bool {
  left.sameBinding(as: right)
    && left.sameMutationState(as: right)
    && left.ownerUID == right.ownerUID
    && left.permissionMode == right.permissionMode
    && left.flags == right.flags
    && left.linkCount == right.linkCount
}

private func descriptorRestoreMatchesHistoricalParent(
  _ snapshot: DescriptorStatSnapshot,
  expected: QuarantineJournalFileBindingV1
) -> Bool {
  guard
    let birthSeconds = Int64(exactly: snapshot.birthSeconds),
    let birthNanoseconds = UInt32(exactly: snapshot.birthNanoseconds),
    let ownerUID = UInt32(exactly: snapshot.ownerUID)
  else {
    return false
  }
  return snapshot.identity.device == expected.device
    && snapshot.identity.inode == expected.inode
    && snapshot.generation == expected.generation
    && birthSeconds == expected.birthSeconds
    && birthNanoseconds == expected.birthNanoseconds
    && snapshot.kind == expected.kind
    && ownerUID == expected.ownerUID
}

private func descriptorRestoreIsLowercaseHexIdentifier(_ value: String) -> Bool {
  let bytes = Array(value.utf8)
  return bytes.count == 32
    && bytes.allSatisfy {
      (0x30...0x39).contains($0) || (0x61...0x66).contains($0)
    }
}

private func descriptorRestoreTransactionIdentifier(_ nonce: [UInt8]) -> String? {
  guard nonce.count == 16 else { return nil }
  let digits = Array("0123456789abcdef".utf8)
  var result = [UInt8]()
  result.reserveCapacity(32)
  for byte in nonce {
    result.append(digits[Int(byte >> 4)])
    result.append(digits[Int(byte & 0x0F)])
  }
  return String(bytes: result, encoding: .utf8)
}

private func descriptorRestoreRandomNonce(_ attempt: Int) -> [UInt8]? {
  _ = attempt
  var bytes = [UInt8](repeating: 0, count: 16)
  bytes.withUnsafeMutableBytes { buffer in
    if let address = buffer.baseAddress {
      Darwin.arc4random_buf(address, buffer.count)
    }
  }
  return bytes
}

private func descriptorRestoreHasExtendedACL(
  _ descriptor: Int32
) -> DescriptorQuarantineDependencyResult<Bool> {
  do {
    return .success(try descriptorHasExtendedACL(descriptor))
  } catch {
    return .failure(descriptorJournalFailure(for: error))
  }
}
